"""empty message

Revision ID: 028018cd8818
Revises: 25fc3f52af44
Create Date: 2017-04-10 23:21:49.523249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028018cd8818'
down_revision = '25fc3f52af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('dnsmasq_static_records', sa.Boolean(), nullable=True))
    op.execute('UPDATE cluster SET dnsmasq_static_records=install_dnsmasq')
    op.alter_column('cluster', 'dnsmasq_static_records', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'dnsmasq_static_records')
    # ### end Alembic commands ###
