"""empty message

Revision ID: 36d4fb7d5e36
Revises: 92f518191c12
Create Date: 2017-04-27 19:07:25.231606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d4fb7d5e36'
down_revision = '92f518191c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('hosts_use_k8s_dns', sa.Boolean(), nullable=True))
    op.execute('UPDATE cluster SET hosts_use_k8s_dns=install_dnsmasq')
    op.execute('UPDATE cluster SET install_dnsmasq=dnsmasq_static_records')
    op.drop_column('cluster', 'dnsmasq_static_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('dnsmasq_static_records', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('cluster', 'hosts_use_k8s_dns')
    # ### end Alembic commands ###
