"""empty message

Revision ID: 74a35a9d4cce
Revises: 
Create Date: 2017-03-12 21:56:57.528018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a35a9d4cce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cert', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ca_credentials_id', sa.Integer(), nullable=False),
    sa.Column('coreos_channel', sa.String(length=80), nullable=False),
    sa.Column('coreos_version', sa.String(length=80), nullable=False),
    sa.Column('etcd_version', sa.Integer(), nullable=False),
    sa.Column('manage_etc_hosts', sa.Boolean(), nullable=False),
    sa.Column('allow_unsafe_credentials_transfer', sa.Boolean(), nullable=False),
    sa.Column('k8s_runtime', sa.Integer(), nullable=False),
    sa.Column('k8s_pod_network', sa.String(length=80), nullable=False),
    sa.Column('k8s_service_network', sa.String(length=80), nullable=False),
    sa.Column('k8s_hyperkube_tag', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['ca_credentials_id'], ['credentials_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=False),
    sa.Column('fqdn', sa.String(length=80), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('credentials_id', sa.Integer(), nullable=False),
    sa.Column('target_config_version', sa.Integer(), nullable=False),
    sa.Column('active_config_version', sa.Integer(), nullable=True),
    sa.Column('active_ignition_config', sa.Text(), nullable=False),
    sa.Column('_coreos_channel', sa.String(length=80), nullable=False),
    sa.Column('_coreos_version', sa.String(length=80), nullable=False),
    sa.Column('coreos_autologin', sa.Boolean(), nullable=False),
    sa.Column('root_disk', sa.String(length=80), nullable=False),
    sa.Column('linux_consoles', sa.String(length=80), nullable=False),
    sa.Column('disable_ipv6', sa.Boolean(), nullable=False),
    sa.Column('is_etcd_server', sa.Boolean(), nullable=False),
    sa.Column('is_k8s_schedulable', sa.Boolean(), nullable=False),
    sa.Column('is_k8s_apiserver', sa.Boolean(), nullable=False),
    sa.Column('is_k8s_apiserver_lb', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fqdn'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('credentials_id', sa.Integer(), nullable=False),
    sa.Column('ssh_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['credentials_id'], ['credentials_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('node')
    op.drop_table('cluster')
    op.drop_table('credentials_data')
    # ### end Alembic commands ###
