"""empty message

Revision ID: b70159a8c7c2
Revises: c821404e777f
Create Date: 2017-04-13 00:19:37.040664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70159a8c7c2'
down_revision = '028018cd8818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('debug_boot', sa.Boolean(), nullable=False, server_default='FALSE'))
    op.alter_column('node', 'debug_boot', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'debug_boot')
    # ### end Alembic commands ###
