"""empty message

Revision ID: bf3ac4dda2ab
Revises: 9a65898a0e2f
Create Date: 2017-04-30 19:28:10.308314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3ac4dda2ab'
down_revision = '9a65898a0e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'allow_insecure_provision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('allow_insecure_provision', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
