"""empty message

Revision ID: da3084151a1d
Revises: f08e29e85dc0
Create Date: 2017-04-28 16:55:46.427969

"""
from alembic import op
import sqlalchemy as sa

from seedbox import config


# revision identifiers, used by Alembic.
revision = 'da3084151a1d'
down_revision = 'f08e29e85dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('etcd_image_tag', sa.String(length=80), nullable=False,
                                       server_default=config.default_etcd_image_tag))
    op.alter_column('cluster', 'etcd_image_tag', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'etcd_image_tag')
    # ### end Alembic commands ###
