"""empty message

Revision ID: 03314dc2f789
Revises: 235f683efac0
Create Date: 2017-06-19 15:39:34.872360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03314dc2f789'
down_revision = '235f683efac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster', sa.Column('docker_config', sa.Text(), nullable=False, server_default='{}'))
    op.alter_column('cluster', 'docker_config', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster', 'docker_config')
    # ### end Alembic commands ###
