"""empty message

Revision ID: 2093be28531b
Revises: da3084151a1d
Create Date: 2017-04-28 18:55:40.347204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2093be28531b'
down_revision = 'da3084151a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('additional_kernel_cmdline', sa.String(length=255), nullable=False,
                                    server_default=''))
    op.alter_column('node', 'additional_kernel_cmdline', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'additional_kernel_cmdline')
    # ### end Alembic commands ###
