"""empty message

Revision ID: 235f683efac0
Revises: 35099fc974d2
Create Date: 2017-05-19 18:46:59.356128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235f683efac0'
down_revision = '35099fc974d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_node_mountpoint_what_uc', 'mountpoint', ['node_id', 'what'])
    op.create_unique_constraint('_node_mountpoint_where_uc', 'mountpoint', ['node_id', 'where'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_node_mountpoint_where_uc', 'mountpoint', type_='unique')
    op.drop_constraint('_node_mountpoint_what_uc', 'mountpoint', type_='unique')
    # ### end Alembic commands ###
