"""empty message

Revision ID: 450edaa5f10d
Revises: bf3ac4dda2ab
Create Date: 2017-04-30 21:33:02.865692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450edaa5f10d'
down_revision = 'bf3ac4dda2ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cluster', 'suppose_etcd_cluster_exists', new_column_name='assert_etcd_cluster_exists')
    op.alter_column('cluster', 'apiservers_audit_log', new_column_name='k8s_apiservers_audit_log')
    op.alter_column('cluster', 'apiservers_swagger_ui', new_column_name='k8s_apiservers_swagger_ui')
    op.alter_column('node', 'root_disk_size_sectors', new_column_name='root_partition_size_sectors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'root_partition_size_sectors', new_column_name='root_disk_size_sectors')
    op.alter_column('cluster', 'k8s_apiservers_swagger_ui', new_column_name='apiservers_swagger_ui')
    op.alter_column('cluster', 'assert_etcd_cluster_exists', new_column_name='suppose_etcd_cluster_exists')
    op.alter_column('cluster', 'k8s_apiservers_audit_log', new_column_name='apiservers_audit_log')
    # ### end Alembic commands ###
