"""empty message

Revision ID: 519c11fc090d
Revises: 579f89f6b1a0
Create Date: 2017-05-19 15:37:45.597324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519c11fc090d'
down_revision = '579f89f6b1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=False),
    sa.Column('wipe_next_boot', sa.Boolean(), nullable=False),
    sa.Column('sector_size_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'device', name='_node_disk_device_uc')
    )

    op.create_table('disk_partition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disk_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('size_mibs', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['disk_id'], ['disk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disk_id', 'label', name='_disk_partition_label_uc'),
    sa.UniqueConstraint('disk_id', 'number', name='_disk_partition_number_uc')
    )

    op.add_column('mountpoint', sa.Column('is_persistent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mountpoint', 'is_persistent')
    op.drop_table('disk_partition')
    op.drop_table('disk')
    # ### end Alembic commands ###
