"""empty message

Revision ID: 52e82e7e9376
Revises: 635f6467bb33
Create Date: 2017-05-01 08:35:20.772434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e82e7e9376'
down_revision = '635f6467bb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_cluster_name_uc', 'user', ['cluster_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_cluster_name_uc', 'user', type_='unique')
    # ### end Alembic commands ###
