"""empty message

Revision ID: 635f6467bb33
Revises: 469154bafe22
Create Date: 2017-04-30 22:39:13.776090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635f6467bb33'
down_revision = '469154bafe22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'groups', new_column_name='k8s_groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'k8s_groups', new_column_name='groups')
    # ### end Alembic commands ###
