"""empty message

Revision ID: aa55bedebb6f
Revises: 2093be28531b
Create Date: 2017-04-28 23:30:59.720792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa55bedebb6f'
down_revision = '2093be28531b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE node SET active_config_version=0 WHERE active_config_version IS NULL')
    op.alter_column('node', 'active_config_version', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'active_config_version', nullable=True)
    # ### end Alembic commands ###
