#!/bin/bash -ex

function init_flannel {
  echo "Waiting for etcd..."
  while true
  do
      for ETCD in {{ etcd_endpoints|join(' ') }}; do
          echo "Trying: $ETCD"
          if [ -n "$(curl --fail --silent --show-error "$ETCD/v2/machines")" ]; then
              local ACTIVE_ETCD=$ETCD
              break
          fi
          sleep 1
      done
      if [ -n "$ACTIVE_ETCD" ]; then
          break
      fi
  done
  RES=$(curl --fail --silent --show-error -X PUT -d "value={\"Network\":\"{{ pod_network }}\",\"Backend\":{\"Type\":\"vxlan\"}}" "$ACTIVE_ETCD/v2/keys/coreos.com/network/config?prevExist=false")
  if [ -z "$(echo $RES | grep '"action":"create"')" ] && [ -z "$(echo $RES | grep 'Key already exists')" ]; then
      echo "Unexpected error configuring flannel pod network: $RES"
  fi
}

init_flannel
