apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: nailgun/kube-scheduler-amd64:{{ kube_scheduler_tag }}
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:{{ config.k8s_apiserver_insecure_port }}
    - --leader-elect=true
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
